// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAagTBxBMR1sQ7LL16UrT3wsNWr5CNZujc',
    appId: '1:64654885784:web:767d61f9dda41e879ba1ed',
    messagingSenderId: '64654885784',
    projectId: 'expenses-app-a4b6b',
    authDomain: 'expenses-app-a4b6b.firebaseapp.com',
    storageBucket: 'expenses-app-a4b6b.firebasestorage.app',
    measurementId: 'G-YDKD8LEG22',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPOYa6anIcq7dXYkcSXKLrDpFiCsOypTg',
    appId: '1:64654885784:ios:0d915e0a0b739e039ba1ed',
    messagingSenderId: '64654885784',
    projectId: 'expenses-app-a4b6b',
    storageBucket: 'expenses-app-a4b6b.firebasestorage.app',
    iosClientId: '64654885784-mgaid6apo70n6lvv6rtd191r3acqonlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPOYa6anIcq7dXYkcSXKLrDpFiCsOypTg',
    appId: '1:64654885784:ios:0d915e0a0b739e039ba1ed',
    messagingSenderId: '64654885784',
    projectId: 'expenses-app-a4b6b',
    storageBucket: 'expenses-app-a4b6b.firebasestorage.app',
    iosClientId: '64654885784-mgaid6apo70n6lvv6rtd191r3acqonlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAagTBxBMR1sQ7LL16UrT3wsNWr5CNZujc',
    appId: '1:64654885784:web:767d61f9dda41e879ba1ed',
    messagingSenderId: '64654885784',
    projectId: 'expenses-app-a4b6b',
    authDomain: 'expenses-app-a4b6b.firebaseapp.com',
    storageBucket: 'expenses-app-a4b6b.firebasestorage.app',
    measurementId: 'G-YDKD8LEG22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO0F3XHsm3voJgyaucxbiklasIz-TCD2w',
    appId: '1:64654885784:android:51c00efdf1e7eb7b9ba1ed',
    messagingSenderId: '64654885784',
    projectId: 'expenses-app-a4b6b',
    storageBucket: 'expenses-app-a4b6b.firebasestorage.app',
  );

}